//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package br.com.etraining.android.service;

import android.app.Activity;
import android.content.Context;
import android.util.Log;
import android.view.View;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class ExercicioHolder_
    extends ExercicioHolder
{

    private Context context_;
    private static ExercicioHolder_ instance_;

    private ExercicioHolder_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
        ((EtrainingAndroidService_) service).afterSetContentView_();
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        service = EtrainingAndroidService_.getInstance_(context_);
    }

    public static ExercicioHolder_ getInstance_(Context context) {
        if (instance_ == null) {
            instance_ = new ExercicioHolder_(context.getApplicationContext());
        }
        return instance_;
    }

    public void rebind(Context context) {
    }

    @Override
    public void atualizarListaItens() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    ExercicioHolder_.super.atualizarListaItens();
                } catch (RuntimeException e) {
                    Log.e("ExercicioHolder_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

}
